object Versions {
  val scala                   = "2.12.15"
  val delta                   = "3.2.0"
  val spark                   = "3.5.0"
  val scalaLogging            = "3.9.2"
  val pureconfig              = "0.17.4"
  val scopt                   = "3.7.1"
  val scalatest               = "3.2.15"
  val monocle                 = "2.1.0"
  val betterfiles             = "3.9.2"
  val json4s                  = "4.0.3"
  val shapeless               = "2.3.7"
  val h2                      = "1.4.200"
  val postgresql              = "42.7.1"
  val jackson                 = "2.12.2"
  val awsSecretManager        = "2.17.44"
  val awsJavaSdkCore          = "1.12.610"
  val awsJavaSdkSecretManager = "1.12.610"
}
